# Generated by Django 2.2.2 on 2019-06-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пиццa', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelOptions(
            name='pizzashop',
            options={'verbose_name': 'Пиццерия', 'verbose_name_plural': 'Пиццерия'},
        ),
    ]
